### ISSUE TITLE
Why Users as uint?

### ISSUE THREAD

**Issue by pmilanez** [AntoineAugusti/feature-flags#9]
Great PKG, i'm thinking about to use it but the way `Users` is controlled by UINT maybe will require some changes in my side since I'm using UUID as ID for them.

Any reason you choose UINT as ID?

I'm thinking about open a PR to support UUID or string. WDYT?

Cheers!

**Comment by AntoineAugusti** [comment]
It was because I usually went with a `user_id` column with an integer type, auto incremental.

Go ahead if you want to submit a PR extending the possibilities!
